# Generated by Django 4.2.7 on 2025-10-19 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webinars', '0001_initial'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='webinars.webinar'),
        ),
        migrations.AddField(
            model_name='enrollmentreminder',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='enrollmentfeedback',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_feedback', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='platform',
            field=models.ForeignKey(help_text='Platform where enrollment was created (from user.platform)', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='platforms.platform'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='webinars.webinar'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='enrollments.enrollment'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['platform', 'webinar', 'is_active'], name='waitlist_en_platfor_9762d9_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['platform', 'position'], name='waitlist_en_platfor_0b03ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitlistentry',
            unique_together={('user', 'webinar')},
        ),
        migrations.AddIndex(
            model_name='enrollmentreminder',
            index=models.Index(fields=['is_sent', 'scheduled_at'], name='enrollment__is_sent_f3c951_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentreminder',
            index=models.Index(fields=['reminder_type', 'sent_at'], name='enrollment__reminde_133956_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['platform', 'status'], name='enrollments_platfor_29a9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['platform', 'user'], name='enrollments_platfor_28dd65_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['platform', 'enrolled_at'], name='enrollments_platfor_f2ecf5_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status', 'enrolled_at'], name='enrollments_status_0b686c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'webinar')},
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='certificate_certifi_a0a669_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='certificate_verific_8df4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['enrollment', 'timestamp'], name='attendance__enrollm_c81392_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['action', 'timestamp'], name='attendance__action_933ece_idx'),
        ),
    ]
