# Generated by Django 4.2.7 on 2025-10-19 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(db_index=True, help_text='Unique identifier (e.g., compliance_trained, people_skill_training)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('invoice_prefix', models.CharField(blank=True, help_text="Invoice prefix (e.g., 'PSINV' for PeopleSkillTraining). Leave blank to auto-generate.", max_length=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('api_key', models.CharField(db_index=True, editable=False, help_text='API key for platform authentication', max_length=64, unique=True)),
                ('api_key_hash', models.CharField(editable=False, help_text='Hashed version of API key for security', max_length=128, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platforms/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='platforms/favicons/')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('secondary_color', models.CharField(default='#8B5CF6', max_length=7)),
                ('accent_color', models.CharField(default='#10B981', max_length=7)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('payment_settings', models.JSONField(blank=True, default=dict)),
                ('email_settings', models.JSONField(blank=True, default=dict)),
                ('analytics', models.JSONField(blank=True, default=dict)),
                ('allowed_ip_addresses', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'db_table': 'platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_instructors', models.IntegerField(default=0)),
                ('total_attendees', models.IntegerField(default=0)),
                ('total_webinars', models.IntegerField(default=0)),
                ('live_webinars', models.IntegerField(default=0)),
                ('recorded_webinars', models.IntegerField(default=0)),
                ('total_enrollments', models.IntegerField(default=0)),
                ('active_enrollments', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('this_month_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='platforms.platform')),
            ],
            options={
                'verbose_name': 'Platform Statistics',
                'verbose_name_plural': 'Platform Statistics',
                'db_table': 'platform_stats',
            },
        ),
        migrations.CreateModel(
            name='PlatformAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='platforms.platform')),
            ],
            options={
                'verbose_name': 'Platform API Log',
                'verbose_name_plural': 'Platform API Logs',
                'db_table': 'platform_api_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['api_key'], name='platforms_api_key_973857_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['platform_id'], name='platforms_platfor_b31072_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['is_active'], name='platforms_is_acti_606976_idx'),
        ),
        migrations.AddIndex(
            model_name='platformapilog',
            index=models.Index(fields=['platform', 'created_at'], name='platform_ap_platfor_dd9f81_idx'),
        ),
        migrations.AddIndex(
            model_name='platformapilog',
            index=models.Index(fields=['platform', 'endpoint'], name='platform_ap_platfor_c338da_idx'),
        ),
    ]
