# Generated by Django 4.2.7 on 2025-10-19 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformapilog',
            name='authenticated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_api_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='platformapilog',
            index=models.Index(fields=['authenticated_user'], name='platform_ap_authent_e944d0_idx'),
        ),
    ]
