# Generated by Django 4.2.7 on 2025-10-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_platformapilog_authenticated_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='email_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Encrypted email configuration including SMTP credentials'),
        ),
    ]
