# Generated by Django 4.2.7 on 2025-10-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_alter_platform_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Admin contact email for BCC notifications (payment confirmations, system alerts)', max_length=254),
        ),
        migrations.AlterField(
            model_name='platform',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Public support email for customer inquiries', max_length=254),
        ),
    ]
