# Generated by Django 4.2.7 on 2025-11-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_platform_contact_email_alter_platform_support_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='email_delivery_method',
            field=models.CharField(choices=[('smtp', 'Direct SMTP'), ('sendgrid_api', 'SendGrid API'), ('mailgun_api', 'Mailgun API'), ('aws_ses_api', 'AWS SES API'), ('resend_api', 'Resend API'), ('postmark_api', 'Postmark API'), ('brevo_api', 'Brevo API')], default='smtp', help_text='Method for sending emails: Direct SMTP or API-based service', max_length=20),
        ),
    ]
