# Generated by Django 4.2.7 on 2025-12-17 04:09

import apps.platforms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_platform_email_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.platforms.models.platform_favicon_upload_path),
        ),
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.platforms.models.platform_logo_upload_path),
        ),
    ]
