# Generated by Django 4.2.7 on 2025-12-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_alter_platform_favicon_alter_platform_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='requires_email_verification',
            field=models.BooleanField(default=True, help_text='If True, users must verify email before login. If False, users are auto-verified on registration.'),
        ),
    ]
