# Generated by Django 4.2.7 on 2025-10-19 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webinars', '0001_initial'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomwebinar',
            name='webinar',
            field=models.ForeignKey(blank=True, help_text='Associated webinar (one Zoom webinar can be shared across multiple webinars)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_webinars', to='webinars.webinar'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhookevent',
            index=models.Index(fields=['event_type'], name='zoom_webhoo_event_t_a16fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhookevent',
            index=models.Index(fields=['processed'], name='zoom_webhoo_process_16c843_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhookevent',
            index=models.Index(fields=['created_at'], name='zoom_webhoo_created_90ab72_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhookevent',
            index=models.Index(fields=['priority'], name='zoom_webhoo_priorit_411f46_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhookevent',
            index=models.Index(fields=['zoom_meeting_id'], name='zoom_webhoo_zoom_me_6f74e7_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhookevent',
            index=models.Index(fields=['zoom_webinar_id'], name='zoom_webhoo_zoom_we_5e1085_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhookevent',
            index=models.Index(fields=['processed', 'processing_attempts'], name='zoom_webhoo_process_cbe002_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhookevent',
            index=models.Index(fields=['processed', 'priority', 'created_at'], name='zoom_webhoo_process_598dde_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhookevent',
            index=models.Index(fields=['requires_retry', 'retry_after'], name='zoom_webhoo_require_2cd3a1_idx'),
        ),
        migrations.AddField(
            model_name='zoomrecording',
            name='zoom_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='integrations.zoommeeting'),
        ),
        migrations.AddField(
            model_name='zoomrecording',
            name='zoom_webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='integrations.zoomwebinar'),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_zoom_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='webinar',
            field=models.ForeignKey(blank=True, help_text='Associated webinar (one Zoom meeting can be shared across multiple webinars)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to='webinars.webinar'),
        ),
        migrations.AddField(
            model_name='zoomintegrationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoom_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='zoomcredentials',
            index=models.Index(fields=['is_active'], name='zoom_creden_is_acti_79857e_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomcredentials',
            index=models.Index(fields=['last_used'], name='zoom_creden_last_us_60fc77_idx'),
        ),
        migrations.AddConstraint(
            model_name='zoomcredentials',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_zoom_credentials'),
        ),
        migrations.AddIndex(
            model_name='zoomwebinar',
            index=models.Index(fields=['zoom_webinar_id'], name='zoom_webina_zoom_we_8aab04_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebinar',
            index=models.Index(fields=['host_id'], name='zoom_webina_host_id_eacc91_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebinar',
            index=models.Index(fields=['status'], name='zoom_webina_status_625ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebinar',
            index=models.Index(fields=['start_time'], name='zoom_webina_start_t_2fccf2_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebinar',
            index=models.Index(fields=['created_by'], name='zoom_webina_created_a0233b_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebinar',
            index=models.Index(fields=['status', 'start_time'], name='zoom_webina_status_42a0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebinar',
            index=models.Index(fields=['webinar', 'status'], name='zoom_webina_webinar_69bd72_idx'),
        ),
        migrations.AddConstraint(
            model_name='zoomwebinar',
            constraint=models.UniqueConstraint(fields=('webinar', 'zoom_webinar_id'), name='unique_webinar_zoom_webinar'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['recording_id'], name='zoom_record_recordi_711bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['meeting_id'], name='zoom_record_meeting_b1d134_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['status'], name='zoom_record_status_b441e3_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['recording_start'], name='zoom_record_recordi_0aea44_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['is_primary_recording'], name='zoom_record_is_prim_c95d25_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['auto_converted'], name='zoom_record_auto_co_778fea_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['status', 'recording_start'], name='zoom_record_status_9f4a27_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['recording_type', 'status'], name='zoom_record_recordi_a7088c_idx'),
        ),
        migrations.AddConstraint(
            model_name='zoomrecording',
            constraint=models.CheckConstraint(check=models.Q(('zoom_meeting__isnull', False), ('zoom_webinar__isnull', False), _connector='OR'), name='recording_must_have_meeting_or_webinar'),
        ),
        migrations.AddIndex(
            model_name='zoommeeting',
            index=models.Index(fields=['zoom_meeting_id'], name='zoom_meetin_zoom_me_60514d_idx'),
        ),
        migrations.AddIndex(
            model_name='zoommeeting',
            index=models.Index(fields=['host_id'], name='zoom_meetin_host_id_5015a2_idx'),
        ),
        migrations.AddIndex(
            model_name='zoommeeting',
            index=models.Index(fields=['status'], name='zoom_meetin_status_4ce949_idx'),
        ),
        migrations.AddIndex(
            model_name='zoommeeting',
            index=models.Index(fields=['start_time'], name='zoom_meetin_start_t_e68b71_idx'),
        ),
        migrations.AddIndex(
            model_name='zoommeeting',
            index=models.Index(fields=['created_by'], name='zoom_meetin_created_0aa1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='zoommeeting',
            index=models.Index(fields=['status', 'start_time'], name='zoom_meetin_status_a5657a_idx'),
        ),
        migrations.AddIndex(
            model_name='zoommeeting',
            index=models.Index(fields=['webinar', 'status'], name='zoom_meetin_webinar_43a9ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='zoommeeting',
            constraint=models.UniqueConstraint(fields=('webinar', 'zoom_meeting_id'), name='unique_webinar_zoom_meeting'),
        ),
        migrations.AddIndex(
            model_name='zoomintegrationlog',
            index=models.Index(fields=['level'], name='zoom_integr_level_cd6134_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomintegrationlog',
            index=models.Index(fields=['action_type'], name='zoom_integr_action__70feee_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomintegrationlog',
            index=models.Index(fields=['created_at'], name='zoom_integr_created_56c2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomintegrationlog',
            index=models.Index(fields=['user'], name='zoom_integr_user_id_9b344a_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomintegrationlog',
            index=models.Index(fields=['zoom_meeting_id'], name='zoom_integr_zoom_me_b599bd_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomintegrationlog',
            index=models.Index(fields=['zoom_webinar_id'], name='zoom_integr_zoom_we_bea41e_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomintegrationlog',
            index=models.Index(fields=['webinar_id'], name='zoom_integr_webinar_edb673_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomintegrationlog',
            index=models.Index(fields=['level', 'created_at'], name='zoom_integr_level_1ef4a3_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomintegrationlog',
            index=models.Index(fields=['action_type', 'created_at'], name='zoom_integr_action__bdf583_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomintegrationlog',
            index=models.Index(fields=['level', 'action_type'], name='zoom_integr_level_ed9b2d_idx'),
        ),
    ]
