# Generated by Django 4.2.7 on 2025-10-19 04:54

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Learning interests like Data Science, Web Development, etc.', size=20)),
                ('learning_goals', models.TextField(blank=True, help_text='What the attendee wants to achieve through learning')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('company', models.CharField(blank=True, help_text='Current organization or company', max_length=200)),
                ('total_enrollments', models.IntegerField(default=0)),
                ('completed_webinars', models.IntegerField(default=0)),
                ('total_hours_learned', models.IntegerField(default=0)),
                ('certificates_earned', models.IntegerField(default=0)),
                ('average_rating_given', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('show_email_publicly', models.BooleanField(default=False)),
                ('show_phone_publicly', models.BooleanField(default=False)),
                ('allow_direct_messages', models.BooleanField(default=True)),
                ('allow_newsletters', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese')], default='en', max_length=5)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('email_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Summary'), ('never', 'Never')], default='immediate', max_length=20)),
                ('auto_join_webinars', models.BooleanField(default=False)),
                ('show_profile_publicly', models.BooleanField(default=True)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(help_text='Platform this attendee belongs to (from user.platform)', on_delete=django.db.models.deletion.CASCADE, related_name='attendee_profiles', to='platforms.platform')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'attendee'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendee Profile',
                'verbose_name_plural': 'Attendee Profiles',
                'db_table': 'attendee_profiles',
            },
        ),
        migrations.CreateModel(
            name='AttendeeSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=32)),
                ('backup_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=10)),
                ('login_alerts_enabled', models.BooleanField(default=True)),
                ('password_changed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to='attendees.attendeeprofile')),
            ],
            options={
                'verbose_name': 'Attendee Security Settings',
                'verbose_name_plural': 'Attendee Security Settings',
                'db_table': 'attendee_security_settings',
            },
        ),
        migrations.CreateModel(
            name='AttendeeNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_webinar_reminders', models.BooleanField(default=True)),
                ('email_new_webinar_alerts', models.BooleanField(default=True)),
                ('email_payment_confirmations', models.BooleanField(default=True)),
                ('email_weekly_digest', models.BooleanField(default=False)),
                ('email_promotional', models.BooleanField(default=False)),
                ('sms_webinar_reminders', models.BooleanField(default=True)),
                ('sms_payment_alerts', models.BooleanField(default=True)),
                ('sms_security_alerts', models.BooleanField(default=True)),
                ('push_webinar_starting', models.BooleanField(default=True)),
                ('push_new_messages', models.BooleanField(default=True)),
                ('push_system_updates', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='attendees.attendeeprofile')),
            ],
            options={
                'verbose_name': 'Attendee Notification Settings',
                'verbose_name_plural': 'Attendee Notification Settings',
                'db_table': 'attendee_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='AttendeeLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', max_length=20)),
                ('total_webinars', models.IntegerField(default=0)),
                ('completed_webinars', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='attendees.attendeeprofile')),
            ],
            options={
                'verbose_name': 'Learning Path',
                'verbose_name_plural': 'Learning Paths',
                'db_table': 'attendee_learning_paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendeeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('enrollment', 'Enrolled in Webinar'), ('completion', 'Completed Webinar'), ('certificate_earned', 'Certificate Earned'), ('profile_update', 'Profile Updated'), ('rating_given', 'Rating Given'), ('comment_posted', 'Comment Posted'), ('login', 'Login'), ('logout', 'Logout')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='attendees.attendeeprofile')),
            ],
            options={
                'verbose_name': 'Attendee Activity',
                'verbose_name_plural': 'Attendee Activities',
                'db_table': 'attendee_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendeeprofile',
            index=models.Index(fields=['platform', 'skill_level'], name='attendee_pr_platfor_e863c8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendeeprofile',
            index=models.Index(fields=['platform', 'created_at'], name='attendee_pr_platfor_cabe50_idx'),
        ),
        migrations.AddIndex(
            model_name='attendeeactivity',
            index=models.Index(fields=['attendee', 'activity_type'], name='attendee_ac_attende_4f5ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendeeactivity',
            index=models.Index(fields=['attendee', 'created_at'], name='attendee_ac_attende_016a30_idx'),
        ),
    ]
