# Generated by Django 4.2.7 on 2025-12-01 11:13

import apps.payments.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cashfree', 'Cashfree'), ('payu', 'PayU')], max_length=50)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Raw gateway response for debugging')),
                ('invoice_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated on payment completion', max_length=50, null=True, unique=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount that has been refunded', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.CharField(choices=[('razorpay', 'Razorpay'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cashfree', 'Cashfree'), ('payu', 'PayU')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this gateway')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Use test/sandbox mode')),
                ('logo_url', models.URLField(blank=True, help_text='URL to gateway logo image')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which gateways appear (0 = first)')),
                ('configuration', models.JSONField(default=apps.payments.models.get_default_configuration, help_text='Gateway-specific configuration (API keys, etc.)')),
                ('supports_refunds', models.BooleanField(default=True)),
                ('supports_partial_refunds', models.BooleanField(default=True)),
                ('supports_webhooks', models.BooleanField(default=True)),
                ('supported_currencies', models.JSONField(default=apps.payments.models.get_default_currencies, help_text='List of supported currencies')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_amount', models.DecimalField(decimal_places=2, default=100000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('processing_time', models.CharField(default='Instant', max_length=50)),
                ('processing_fee_percentage', models.DecimalField(decimal_places=4, default=0.02, help_text='Processing fee as decimal (0.02 = 2%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'db_table': 'payment_gateways',
                'ordering': ['display_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(db_index=True, max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('webhook_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Webhook',
                'verbose_name_plural': 'Payment Webhooks',
                'db_table': 'payment_webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('access_type', models.CharField(default='liveOne', help_text='liveOne, liveGroup, recordedOne, recordedGroup, comboOne, comboGroup', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Webinar',
                'verbose_name_plural': 'Payment Webinars',
                'db_table': 'payment_webinars',
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('admin_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway_refund_id', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Refund Request',
                'verbose_name_plural': 'Refund Requests',
                'db_table': 'refund_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
