# Generated by Django 4.2.7 on 2025-12-01 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('webinars', '0001_initial'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentwebinar',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_webinars', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentwebinar',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_webinars', to='webinars.webinar'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['gateway', 'processed'], name='payment_web_gateway_1e18a0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['webhook_id'], name='payment_web_webhook_83caa2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['processed', 'created_at'], name='payment_web_process_79839b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentgateway',
            unique_together={('gateway_id', 'is_test_mode')},
        ),
        migrations.AddField(
            model_name='payment',
            name='platform',
            field=models.ForeignKey(help_text='Platform where payment was made', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='platforms.platform'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='webinar',
            field=models.ForeignKey(blank=True, help_text='Backward compatibility', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_payments', to='webinars.webinar'),
        ),
        migrations.AddField(
            model_name='payment',
            name='webinars',
            field=models.ManyToManyField(related_name='payments', through='payments.PaymentWebinar', to='webinars.webinar'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status', 'requested_at'], name='refund_requ_status_d5d361_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebinar',
            index=models.Index(fields=['payment', 'webinar'], name='payment_web_payment_420f7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentwebinar',
            unique_together={('payment', 'webinar', 'access_type')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['platform', 'status'], name='payments_platfor_9b3d14_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['platform', 'user'], name='payments_platfor_6e2b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice_number'], name='payments_invoice_2de10a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
    ]
