# Generated by Django 4.2.7 on 2025-12-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_platform_email_delivery_method'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'ordering': ['platform', 'display_order', 'display_name'], 'verbose_name': 'Payment Gateway', 'verbose_name_plural': 'Payment Gateways'},
        ),
        migrations.AlterUniqueTogether(
            name='paymentgateway',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='platform',
            field=models.ForeignKey(blank=True, help_text='Platform that owns this gateway', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='platforms.platform'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentgateway',
            unique_together={('platform', 'gateway_id', 'is_test_mode')},
        ),
    ]
