# Generated by Django 4.2.7 on 2025-12-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentgateway_options_and_more'),
    ]

    operations = [
    ]
