# Generated by Django 4.2.7 on 2025-12-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_populate_platform_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentgateway',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='paymentgateway',
            constraint=models.UniqueConstraint(fields=('platform', 'gateway_id', 'is_test_mode'), name='unique_platform_gateway'),
        ),
        migrations.AddConstraint(
            model_name='paymentgateway',
            constraint=models.UniqueConstraint(condition=models.Q(('platform__isnull', True)), fields=('gateway_id', 'is_test_mode'), name='unique_global_gateway'),
        ),
    ]
