# Generated by Django 4.2.7 on 2025-10-19 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username_key', models.CharField(db_index=True, editable=False, help_text='Composite key: email::platform_id (auto-generated)', max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Email address (used for login)', max_length=255, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/%Y/%m/')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('company', models.CharField(blank=True, help_text='Company or organization name', max_length=255, verbose_name='company name')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor'), ('attendee', 'Attendee')], db_index=True, default='attendee', help_text='User role in the system', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site.', verbose_name='staff status')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether email has been verified.', verbose_name='verified')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='email verified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('platform', models.ForeignKey(blank=True, help_text='Platform for attendees only. NULL for admins/instructors', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='platforms.platform')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='biography')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='timezone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('show_email_publicly', models.BooleanField(default=False, verbose_name='show email publicly')),
                ('show_phone_publicly', models.BooleanField(default=False, verbose_name='show phone publicly')),
                ('allow_direct_messages', models.BooleanField(default=True, verbose_name='allow direct messages')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='preferences')),
                ('notification_settings', models.JSONField(blank=True, default=dict, verbose_name='notification settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username_key'], name='idx_username_key'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['platform', 'role'], name='idx_platform_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='idx_role_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_verified'], name='idx_active_verified'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['admin', 'instructor'])), fields=('email',), name='unique_email_for_shared_users'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'attendee')), fields=('email', 'platform'), name='unique_email_per_platform_for_attendees'),
        ),
    ]
