# Generated by Django 4.2.7 on 2025-10-19 04:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speakers', '0001_initial'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'webinar_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_id', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all-levels', 'All Levels')], db_index=True, default='beginner', max_length=20)),
                ('webinar_type', models.CharField(choices=[('live', 'Live Webinar'), ('recorded', 'Recorded Only')], db_index=True, default='live', help_text='Live: Creates Zoom meeting | Recorded: Direct Zoom URL', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes (required for live webinars)', null=True, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=50)),
                ('zoom_url', models.URLField(blank=True, help_text='Direct Zoom URL for recorded webinars or auto-added recordings')),
                ('auto_convert_to_recorded', models.BooleanField(default=True, help_text='Auto-add recording URL when live webinar completes')),
                ('has_recording', models.BooleanField(db_index=True, default=False, help_text='Whether this webinar has recordings available')),
                ('recording_check_count', models.IntegerField(default=0, help_text="Number of times we've checked for recordings")),
                ('last_recording_check', models.DateTimeField(blank=True, help_text='Last time we checked for recordings', null=True)),
                ('has_enrollment_limit', models.BooleanField(default=False)),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('pricing_data', models.JSONField(blank=True, default=dict)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='webinar_covers/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('available', 'Available'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('zoom_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webinars.category')),
                ('platforms', models.ManyToManyField(blank=True, help_text='Platforms where this webinar is available (leave empty for all platforms)', related_name='webinars', to='platforms.platform')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to='speakers.speaker')),
            ],
            options={
                'verbose_name': 'Webinar',
                'verbose_name_plural': 'Webinars',
                'db_table': 'webinars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('session_number', models.PositiveIntegerField(db_index=True)),
                ('scheduled_date', models.DateTimeField(db_index=True)),
                ('duration', models.IntegerField()),
                ('zoom_meeting_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('zoom_join_url', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'Webinar Session',
                'verbose_name_plural': 'Webinar Sessions',
                'db_table': 'webinar_sessions',
                'ordering': ['session_number'],
            },
        ),
        migrations.CreateModel(
            name='WebinarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(db_index=True, help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('content_quality', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('instructor_performance', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('technical_quality', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('would_recommend', models.BooleanField(db_index=True, default=True)),
                ('is_verified_purchase', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_reviews', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'Webinar Review',
                'verbose_name_plural': 'Webinar Reviews',
                'db_table': 'webinar_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('link', 'External Link'), ('other', 'Other')], db_index=True, default='pdf', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='webinar_resources/')),
                ('url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'Webinar Resource',
                'verbose_name_plural': 'Webinar Resources',
                'db_table': 'webinar_resources',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WebinarPlatformPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_data', models.JSONField(blank=True, default=dict, help_text='Platform-specific pricing override')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage for this platform', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_prices', to='platforms.platform')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_prices', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'Webinar Platform Price',
                'verbose_name_plural': 'Webinar Platform Prices',
                'db_table': 'webinar_platform_prices',
                'ordering': ['platform__name'],
            },
        ),
        migrations.CreateModel(
            name='WebinarAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.IntegerField(db_index=True, default=0)),
                ('total_attendees', models.IntegerField(db_index=True, default=0)),
                ('peak_concurrent_attendees', models.IntegerField(default=0)),
                ('average_attendance_duration', models.IntegerField(default=0)),
                ('total_questions_asked', models.IntegerField(default=0)),
                ('total_chat_messages', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('webinar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'Webinar Analytics',
                'verbose_name_plural': 'Webinar Analytics',
                'db_table': 'webinar_analytics',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='webinar_cat_name_dcc236_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='webinar_cat_is_acti_d55b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarsession',
            index=models.Index(fields=['webinar'], name='webinar_ses_webinar_52035f_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarsession',
            index=models.Index(fields=['session_number'], name='webinar_ses_session_bd6f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarsession',
            index=models.Index(fields=['scheduled_date'], name='webinar_ses_schedul_40f358_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarsession',
            index=models.Index(fields=['zoom_meeting_id'], name='webinar_ses_zoom_me_064460_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarsession',
            index=models.Index(fields=['is_completed'], name='webinar_ses_is_comp_bbe333_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarsession',
            index=models.Index(fields=['webinar', 'session_number'], name='webinar_ses_webinar_f6f6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarsession',
            index=models.Index(fields=['webinar', 'is_completed'], name='webinar_ses_webinar_973b6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webinarsession',
            unique_together={('webinar', 'session_number')},
        ),
        migrations.AddIndex(
            model_name='webinarreview',
            index=models.Index(fields=['webinar'], name='webinar_rev_webinar_dec5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarreview',
            index=models.Index(fields=['user'], name='webinar_rev_user_id_69d385_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarreview',
            index=models.Index(fields=['rating'], name='webinar_rev_rating_10893a_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarreview',
            index=models.Index(fields=['would_recommend'], name='webinar_rev_would_r_87487d_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarreview',
            index=models.Index(fields=['is_verified_purchase'], name='webinar_rev_is_veri_bbe30d_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarreview',
            index=models.Index(fields=['created_at'], name='webinar_rev_created_78d12b_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarreview',
            index=models.Index(fields=['webinar', 'rating'], name='webinar_rev_webinar_5de1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarreview',
            index=models.Index(fields=['webinar', 'is_verified_purchase'], name='webinar_rev_webinar_a4132f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webinarreview',
            unique_together={('webinar', 'user')},
        ),
        migrations.AddIndex(
            model_name='webinarresource',
            index=models.Index(fields=['webinar'], name='webinar_res_webinar_f4ea0f_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarresource',
            index=models.Index(fields=['title'], name='webinar_res_title_cc2835_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarresource',
            index=models.Index(fields=['resource_type'], name='webinar_res_resourc_2471c0_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarresource',
            index=models.Index(fields=['is_public'], name='webinar_res_is_publ_3e56e3_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarresource',
            index=models.Index(fields=['uploaded_at'], name='webinar_res_uploade_ad0381_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarresource',
            index=models.Index(fields=['webinar', 'is_public'], name='webinar_res_webinar_7b8cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarresource',
            index=models.Index(fields=['webinar', 'resource_type'], name='webinar_res_webinar_2d751b_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarplatformprice',
            index=models.Index(fields=['webinar', 'platform'], name='webinar_pla_webinar_3f3baf_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarplatformprice',
            index=models.Index(fields=['platform', 'is_active'], name='webinar_pla_platfor_b35d27_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarplatformprice',
            index=models.Index(fields=['is_active'], name='webinar_pla_is_acti_a0f158_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webinarplatformprice',
            unique_together={('webinar', 'platform')},
        ),
        migrations.AddIndex(
            model_name='webinaranalytics',
            index=models.Index(fields=['total_enrollments'], name='webinar_ana_total_e_938409_idx'),
        ),
        migrations.AddIndex(
            model_name='webinaranalytics',
            index=models.Index(fields=['total_attendees'], name='webinar_ana_total_a_b45068_idx'),
        ),
        migrations.AddIndex(
            model_name='webinaranalytics',
            index=models.Index(fields=['average_rating'], name='webinar_ana_average_79be72_idx'),
        ),
        migrations.AddIndex(
            model_name='webinaranalytics',
            index=models.Index(fields=['total_revenue'], name='webinar_ana_total_r_65d621_idx'),
        ),
        migrations.AddIndex(
            model_name='webinaranalytics',
            index=models.Index(fields=['last_updated'], name='webinar_ana_last_up_a2f145_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['webinar_id'], name='webinars_webinar_761055_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['title'], name='webinars_title_aa90a0_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['speaker'], name='webinars_speaker_1799a7_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['category'], name='webinars_categor_8ad938_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['skill_level'], name='webinars_skill_l_d91792_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['webinar_type'], name='webinars_webinar_5db24a_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['scheduled_date'], name='webinars_schedul_9023ba_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['status'], name='webinars_status_20cf3e_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['has_recording'], name='webinars_has_rec_c8a9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['created_at'], name='webinars_created_0f6d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['webinar_type', 'status'], name='webinars_webinar_2266dd_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['webinar_type', 'scheduled_date'], name='webinars_webinar_95db9f_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['status', 'scheduled_date'], name='webinars_status_d32dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['speaker', 'status'], name='webinars_speaker_05e685_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['category', 'status'], name='webinars_categor_1e7456_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['has_recording', 'status'], name='webinars_has_rec_183165_idx'),
        ),
    ]
