# Generated by Django 4.2.7 on 2025-10-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='title',
            field=models.CharField(db_index=True, max_length=400),
        ),
    ]
