# Generated by Django 4.2.7 on 2025-12-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0002_alter_webinar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='recording_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete Zoom recording metadata (recording_id, duration, file info, URLs, etc.)'),
        ),
    ]
