# Generated by Django 4.2.7 on 2025-10-19 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webinars', '0001_initial'),
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaranalytics',
            name='webinar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_data', to='webinars.webinar'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_user_activities', to='webinars.webinar'),
        ),
        migrations.AddField(
            model_name='revenueanalytics',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_revenue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenueanalytics',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_revenue', to='webinars.webinar'),
        ),
        migrations.AddIndex(
            model_name='platformmetrics',
            index=models.Index(fields=['date'], name='analytics_p_date_82cc92_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type'], name='analytics_u_user_id_266824_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['timestamp'], name='analytics_u_timesta_2b8b17_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['webinar', 'activity_type'], name='analytics_u_webinar_e1f168_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueanalytics',
            index=models.Index(fields=['date', 'instructor'], name='analytics_r_date_615e37_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueanalytics',
            index=models.Index(fields=['webinar'], name='analytics_r_webinar_8a6a19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revenueanalytics',
            unique_together={('date', 'instructor', 'webinar')},
        ),
    ]
