# Generated by Django 4.2.7 on 2025-10-19 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Professional title or designation', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Professional background and expertise')),
                ('company', models.CharField(blank=True, help_text='Current organization or company', max_length=200)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified speaker status by admin')),
                ('is_active', models.BooleanField(default=True, help_text='Available for new webinars')),
                ('total_sessions', models.PositiveIntegerField(default=0, help_text='Total completed webinar sessions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'db_table': 'speakers',
                'ordering': ['-total_sessions'],
                'indexes': [models.Index(fields=['is_active', 'is_verified'], name='speakers_is_acti_c262f2_idx'), models.Index(fields=['total_sessions'], name='speakers_total_s_335629_idx')],
            },
        ),
    ]
