# Generated by Django 4.2.7 on 2025-10-19 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webinars', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinars.webinar'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_log', to='notifications.notification'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['to_phone', 'sent_at'], name='sms_logs_to_phon_913725_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['platform', 'event_type', 'is_active'], name='notificatio_platfor_e76455_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('template_type', 'event_type', 'platform'), name='unique_template_per_platform'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('platform__isnull', True)), fields=('template_type', 'event_type'), name='unique_global_template'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['platform', 'user', 'status'], name='notificatio_platfor_a9a5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['platform', 'scheduled_at'], name='notificatio_platfor_c91008_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status', 'created_at'], name='notificatio_user_id_286b90_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['template', 'status'], name='notificatio_templat_54b766_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['to_email', 'sent_at'], name='email_logs_to_emai_6c08df_idx'),
        ),
    ]
